#!/bin/bash

function generateImage(){
    cvlc --rc-host localhost:8082 -V dummy --video-filter scene  --no-audio --scene-path $DIR --scene-prefix hdev --scene-format jpg --scene-replace --run-time 1 --deinterlace 1 --deinterlace-mode yadif2x $DIR/playlist.m3u8 & sleep 10 &&  echo quit | nc localhost 8082
}

function imagecomp(){
	compareOutput="$(compare -metric RMSE $DIR/hdev.jpg $DIR/$1 NULL: 2>&1)"
	regex="\(([0-9]\.[0-9]*)\)"
	echo $compareOutput
	if [[ ${compareOutput} =~ ${regex} ]]; then
		matchFloat=${BASH_REMATCH[1]}
		# Can't do floating point math in bash
		matchPercent="$(echo $matchFloat*100/1 | bc)"
		echo $matchPercent
		if  [ $matchPercent -lt 10 ]; then
			echo "HDEV is offline:" $1
			quit
		fi
	fi
}

function quit(){
	killall -9 vlc
	echo "Exiting"
	exit 0
}

# Contains the directory the script is in
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
generateImage

#imagecomp "offline.jpg" 
imagecomp "blank.jpg"
imagecomp "grey.jpg" 
imagecomp "logo.jpg" 

echo "Copying image"
DATE_PATH=$(date +%Y/%m/%d)
TIMESTAMP=$(date +%s)
DEST=/var/www/hdev/$DATE_PATH
mkdir -p $DEST
cp $DIR/hdev.jpg $DEST/$TIMESTAMP.jpg
mv $DIR/hdev.jpg /var/www/hdev/hdev.jpg

quit
